events { 
    worker_connections 1024; 
}

http {
    upstream ollama_cluster {
        # Algoritmo para enviar la petición al MiniPC con menos carga activa
        least_conn; 
        
        # IPs de la subred aislada
        server 10.0.50.11:11434;
        server 10.0.50.12:11434;
        # Añade los demás aquí...
    }

    server {
        listen 11434;
        location / {
            proxy_pass http://ollama_cluster;
            proxy_read_timeout 300;
            proxy_connect_timeout 300;
            proxy_send_timeout 300;
        }
    }
}
